### ISSUE TITLE
Do not use wunderground ip address

### ISSUE THREAD

**Issue by itineric** [mossc001/Bresser-Weather-Station#1]
Wunderground uses AWS so ip address may change over time or with your world location.

Do an nslookup of rtupdate.wunderground.com and you will see it resolves pws-ingest-use1-01.sun.weather.com so you can use this value instead of a non reliable ip address.

Thanks for the work on the rest, it works fine.

**Comment by mossc001** [comment]
@itineric , thanks! I've amended the guide and include the new DNS entry of pws-ingest-use1-01.sun.weather.com for Wunderground.
